/*SQL is a standard language for accessing and manipulating databases.
SQL stands for Structured Query Language
RDBMS is the basis for SQL, and for all modern database systems such 
as MS SQL Server, IBM DB2, Oracle, MySQL, and Microsoft Access.*/

create database SchoolDB;
create databse collegeDB;
DROP DATABASE SchoolDB;//DELETE THE DATABASE
USE collegeDB;//SELECT THE DATABASE TO WORK ON

CREATE TABLE STUDENT(
    ID INT PRIMARY KEY,//PRIMARY KEY IS USED TO UNIQUE IDENTIFY EACH RECORD
    Name VARCHAR(50),//VARCHAR IS USED FOR STRING DATA TYPE 50 IS THE MAXIMUM LENGTH
    Age INT NOT NULL//NAME DATATYE THE CONSTRAINT
);
INSERT INTO STUDENT(ID,Name,Age) VALUES(1,'Rehan',22);
INSERT INTO STUDENT(ID,Name,Age) VALUES(2,'Arafat',23);

SELECT * FROM STUDENT;//SELECT ALL RECORDS FROM STUDENT TABLE

//DATA TYPES IN SQL
//Numeric Data Types: INT, FLOAT, DOUBLE, DECIMAL
//String Data Types: CHAR, VARCHAR, TEXT ,(DIFFERENCE BETWEEN CHAR AND VARCHAR IS CHAR IS FIXED LENGTH 
//AND VARCHAR IS VARIABLE LENGTH)
//BLOB: BINARY LARGE OBJECT --> USE LARGE AMOUNT OF BINARY DATA STRING LIKE IMAGES, AUDIO, ETC FILES
//BIGINT: USED TO STORE VERY LARGE INTEGER VALUES
//BIT : USED TO STORE BINARY VALUES (0 OR 1)
//BOOLEAN : USED TO STORE TRUE OR FALSE VALUES
//DATE AND TIME DATA TYPES: DATE, TIME, DATETIME, TIMESTAMP
//DATE: STORES DATE IN 'YYYY-MM-DD' FORMAT

// DATA TYPE SINGNED AND UNSIGNED
//SIGNED: CAN STORE BOTH POSITIVE AND NEGATIVE VALUES  
//UNSIGNED: CAN STORE ONLY POSITIVE VALUES

## SQL COMMANDS
//DDL: DATA DEFINITION LANGUAGE
CREATE: USED TO CREATE DATABASE AND TABLES
ALTER: USED TO MODIFY THE STRUCTURE OF AN EXISTING TABLE        
DROP: USED TO DELETE DATABASE AND TABLES
TRUNCATE: USED TO DELETE ALL RECORDS FROM A TABLE BUT NOT THE TABLE ITSELF
RENAME: USED TO RENAME A TABLE
//DML: DATA MANIPULATION LANGUAGE
INSERT: USED TO INSERT RECORDS INTO A TABLE
UPDATE: USED TO MODIFY EXISTING RECORDS IN A TABLE
DELETE: USED TO DELETE RECORDS FROM A TABLE
//DQL: DATA QUERY LANGUAGE
SELECT: USED TO RETRIEVE RECORDS FROM A TABLE
** <--IMRPORTANT 
//DCL: DATA CONTROL LANGUAGE
GRANT: USED TO GIVE PRIVILEGES TO USERS
REVOKE: USED TO TAKE BACK PRIVILEGES FROM USERS
//TCL: TRANSACTION CONTROL LANGUAGE
COMMIT: USED TO SAVE TRANSACTIONS
ROLLBACK: USED TO UNDO TRANSACTIONS
SAVEPOINT: USED TO SET A POINT IN TRANSACTION TO WHICH ROLLBACK CAN BE DONE
SET TRANSACTION: USED TO SET TRANSACTION PROPERTIES
//SQL CONSTRAINTS
NOT NULL: USED TO ENSURE A COLUMN CANNOT HAVE NULL VALUES
UNIQUE: USED TO ENSURE ALL VALUES IN A COLUMN ARE UNIQUE
PRIMARY KEY: USED TO UNIQUELY IDENTIFY EACH RECORD IN A TABLE
FOREIGN KEY: USED TO REFERENCE THE PRIMARY KEY OF ANOTHER TABLE
CHECK: USED TO ENSURE ALL VALUES IN A COLUMN SATISFY A SPECIFIC CONDITION
DEFAULT: USED TO SET A DEFAULT VALUE FOR A COLUMN

CREATE DATABASE COLLAGEDB;
CREATE DATABASE IF NOT EXISTS COLLAGEDB;

//SELECT 
SELECT * FROM STUDENT;//FOR SHOW THE TABLE ALL DATA

//INSERT 
INSERT INTO STUDENT(ID,Name,Age) VALUES(3,'Sakib',24),(4,'Rafi',22),(5,'Jahid',23);//LIKE THIS WE CAN INSERT MULTIPLE DATA


## PROBLEM 1

CREATE DATABASE XYZ;
USE XYZ;
CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    SALARY INT
);

INSERT INTO EMPLOYEE(ID,NAME,SALARY) VALUES(1,'ADAM',25000),(2,'BOB',30000);
SELECT * FROM EMPLOYEE;

# KEY 
//PRIMARY KEY: UNIQUELY IDENTIFY EACH RECORD IN A TABLE CAN BE SINGLE OR COMPOSITE
//SINGLE PRIMARY KEY: A PRIMARY KEY THAT CONSISTS OF A SINGLE COLUMN
//COMPOSITE PRIMARY KEY: A PRIMARY KEY THAT CONSISTS OF MULTIPLE COLUMNS

//FOREIGN KEY: REFERENCE THE PRIMARY KEY OF ANOTHER TABLE

## CONSTRAINTS
//NOT NULL: ENSURE A COLUMN CANNOT HAVE NULL VALUES
//UNIQUE: ENSURE ALL VALUES IN A COLUMN ARE UNIQUE
//CHECK: ENSURE ALL VALUES IN A COLUMN SATISFY A SPECIFIC CONDITION
//DEFAULT: SET A DEFAULT VALUE FOR A COLUMN HOW IT WORK LIKE SALLARY DEFAULT 1000
//PRIMARY KEY: UNIQUELY IDENTIFY EACH RECORD IN A TABLE
//FOREIGN KEY: REFERENCE THE PRIMARY KEY OF ANOTHER TABLE
//CHECK CONSTRAINT EXAMPLE
CREATE TABLE EMPLOYEE(
    ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    SALARY INT CHECK(SALARY>=0)//SALLARY CAN NOT BE NEGATIVE
    CONSTRAINT chk_salary CHECK(SALARY>=0)
);

## MULTIPLE PRIMARY KEY
CREATE TABLE DEPARTMENT(
    DEPT_ID INT,
    DEPT_NAME VARCHAR(255),
    PRIMARY KEY(DEPT_ID,DEPT_NAME)
    //COMBINATION UNIQUE HOLE E HOBE
);

//HOW TO DECLARE FOREIGN KEY
CREATE TABLE PROJECT(
    DEPT_ID INT,
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);


## SELECT STATEMENT
SELECT * FROM STUDENT;//SELECT ALL COLUMNS AND ALL ROWS FROM STUDENT TABLE
SELECT NAME, MARK FROM STUDENT;//SELECT SPECIFIC COLUMNS FROM STUDENT TABLE
SELECT DISTINCT CITY FROM STUDENT;//SELECT DISTINCT VALUES FROM CITY COLUMN IN STUDENT TABLE
//HERE WHERE IS CLAUSE THAT MEANS CONDITION
SELECT * FROM STUDENT WHERE AGE>20;//SELECT ALL COLUMNS AND ROWS WHERE AGE

SELECT * FROM STUDENT WHERE MARK>=53;
SELECT * FROM STUDENT WHERE CITY='PATUAKHALI' AND MARK>53;
//NEED OPERATOR
//TYPES OF OPERATORS
//ARITHMETIC OPERATORS: +, -, *, /, %
EXAMPLE:
SELECT * FROM STUDENT WHERE MARK%2=0;//SELECT ALL STUDENT WHOSE MARK IS EVEN
//COMPARISON OPERATORS: =, !=, <, >, <=, >=
EXAMPLE:
SELECT * FROM STUDENT WHERE AGE>=21;//SELECT ALL STUDENT WHOSE AGE IS GRE
//LOGICAL OPERATORS: AND, OR, NOT
EXAMPLE:
SELECT * FROM STUDENT WHERE CITY='DHAKA' OR CITY='CHITTAGONG';
//NOT OPERATOR
SELECT * FROM STUDENT WHERE NOT CITY='DHAKA';//SELECT ALL STUDENT WHO ARE NOT FROM DHAKA
SELCT * FROM STUDENT WHERE NOT IN ('DHAKA','CHITTAGONG');//SELECT ALL STUDENT WHO ARE NOT FROM DHAKA AND CHITTAGONG
//BETWEEN OPERATOR
SELECT * FROM STUDENT WHERE MARK BETWEEN 50 AND 60;//SELECT ALL STUDENT WHOSE MARK IS BETWEEN 50 AND 60
//IN OPERATOR
SELECT * FROM STUDENT WHERE CITY IN('DHAKA','CHITTAGONG','PATUAKHALI');//SELECT ALL STUDENT WHO ARE FROM LIST
//LIMIT CLAUSE
SELECT * FROM STUDENT LIMIT 5;//SELECT FIRST 5 RECORDS FROM STUDENT TABLE

//ORDER BY CLAUSE FOR SORTING
SELECT * FROM STUDENT ORDER BY MARK DESC;//SELECT ALL RECORDS SORTED BY MARK IN DESCENDING ORDER
SELECT * FROM STUDENT ORDER BY NAME ASC;//SELECT ALL RECORDS SORTED BY NAME IN

//AGGREGATE FUNCTIONS
//PERFORM CALCULATIONS ON A SET OF VALUES AND RETURN A SINGLE VALUE
//COUNT(): RETURNS THE NUMBER OF ROWS THAT MATCH A SPECIFIC CONDITION
SELECT COUNT(*) FROM STUDENT;//RETURN THE TOTAL NUMBER OF STUDENT RECORDS
SELECT COUNT(DISTINCT CITY) FROM STUDENT;//RETURN THE NUMBER OF DISTINCT CITIES IN STUDENT TABLE
//SUM(): RETURNS THE SUM OF A NUMERIC COLUMN
SELECT SUM(MARK) FROM STUDENT;//RETURN THE TOTAL SUM OF MARKS OF ALL STUDENTS
//AVG(): RETURNS THE AVERAGE VALUE OF A NUMERIC COLUMN
SELECT AVG(MARK) FROM STUDENT;//RETURN THE AVERAGE MARK OF ALL STUDENTS
//MAX(): RETURNS THE MAXIMUM VALUE IN A COLUMN
SELECT MAX(MARK) FROM STUDENT;//RETURN THE HIGHEST MARK AMONG ALL STUD
//MIN(): RETURNS THE MINIMUM VALUE IN A COLUMN
SELECT MIN(MARK) FROM STUDENT;//RETURN THE LOWEST MARK AMONG ALL STUDENTS


//GROUP BY CLAUSE MEANS TO GROUP ROWS THAT HAVE THE SAME VALUES IN SPECIFIED COLUMNS INTO SUMMARY ROWS
SELECT CITY, COUNT(*) FROM STUDENT GROUP BY CITY;//RETURN THE NUMBER OF STUDENTS IN EACH CITY
SELECT CITY, AVG(MARK) FROM STUDENT GROUP BY CITY;//RETURN THE AVERAGE MARK OF STUDENTS IN EACH CITY
MORE COMPLEX EXAMPLE
    SELECT CITY,
    COUNT(*), AVG(MARK) FROM STUDENT GROUP BY CITY;
//

#PRACTTICE PROBLEM 2
//WRITE A SQL QUERY TO FIND THE AVERAGE MARK OF STUDENTS IN EACH CITY AND
SELECT CITY, AVG(MARK) FROM STUDENT GROUP BY CITY ORDER BY AVG(MARK) ASC;

## HAVING CLAUSE
//USED TO FILTER RECORDS THAT WORK LIKE A WHERE CLAUSE BUT IS USED WITH AGGREGATE FUNCTIONS
SELECT CITY, COUNT(*) FROM STUDENT GROUP BY CITY HAVING COUNT(*)>5;//RETURN CITIES WITH MORE THAN 5 STUDENTS
SELECT CITY, AVG(MARK) FROM STUDENT GROUP BY CITY HAVING AVG(MARK)>50;//RETURN CITIES WHERE AVERAGE MARK IS GREATER THAN 50
WHY WE USE HAVING CLAUSE INSTEAD OF WHERE CLAUSE
//BECAUSE WHERE CLAUSE CANNOT BE USED WITH AGGREGATE FUNCTIONS
//WHILE HAVING CLAUSE IS SPECIFICALLY DESIGNED TO WORK WITH AGGREGATE FUNCTIONS

## CLAUSE ORDER OF EXECUTION
SELECT (COLUMN NAME) --> FROM (TABLE NAME) ->WHERE (CONDITION) -> GROUP BY (COLUMN NAME) -> 
HAVING (CONDITION) -> ORDER BY (COLUMN NAME) -> LIMIT (NUMBER)
EXAMPLE:

SELECT CITY, 
AVG(MARK) 
FROM STUDENT
WHERE AGE>20 
GROUP BY CITY 
HAVING AVG(MARK)>50 
ORDER BY AVG(MARK) DESC 
LIMIT 5;

//UPDATE STATEMENT
UPDATE STUDENT 
SET GRADE = 'A' 
WHERE MARK>=90;//  90

SET SQL_SAFE_UPDATES=0;//TO AVOID ERROR WHEN NO WHERE CLAUSE IS USED

UPDATE STUDENT
SET MARK = 90
WHERE NAME = 'REHAN';

UPDATE STUDENT
SET MARK = MARK + 5
WHERE MARK BETWEEN 50 AND 60;//INCREASE MARK BY 5 FOR STUDENTS WHOSE MARK IS BETWEEN 50 AND 60

//DELETE STATEMENT
DELETE FROM STUDENT
WHERE ID = 5;

//FOREIGEN KEY
EXAPMLE
CREATE TABLE DEPARTMENT(
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(255)
);  
CREATE TABLE EMPLOYEE(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(255),
    DEPT_ID INT,
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

// CASCADE DELETE AND UPDATE
CREATE TABLE EMPLOYEE(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(255),
    DEPT_ID INT,
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
MEANS IF A DEPARTMENT IS DELETED THEN ALL EMPLOYEES IN THAT DEPARTMENT WILL ALSO BE DELETED
//IF DEPT_ID IS UPDATED IN DEPARTMENT TABLE THEN IT WILL ALSO BE UPDATED IN EMPLOYEE TABLE

//ALTER TABLE
//ADD COLUMN
ALTER TABLE STUDENT
ADD COLUMN GRADE VARCHAR(2);//ADD A NEW COLUMN GRADE TO STUDENT TABLE
//DROP COLUMN
ALTER TABLE STUDENT
DROP COLUMN GRADE;//DELETE THE COLUMN GRADE FROM STUDENT TABLE
//MODIFY COLUMN
ALTER TABLE STUDENT     
MODIFY COLUMN NAME VARCHAR(100);//CHANGE THE DATA TYPE OF NAME COLUMN TO VARCHAR(100)
//RENAME TABLE
ALTER TABLE STUDENT 
RENAME TO PUPIL;//RENAME STUDENT TABLE TO PUPIL
//CHANGE COLUMN
ALTER TABLE STUDENT
CHANGE COLUMN MARK SCORE INT;//RENAME COLUMN MARK TO SCORE AND CHANGE ITS DATA TYPE TO INT

TRUNCATE TABLE STUDENT;//DELETE ALL RECORDS FROM STUDENT TABLE BUT KEEP THE TABLE STRUCTURE
//TABLE DATA DELETE HOYE JABE KINTU TABLE THAKBE

//SQL JOINS
//USED TO COMBINE ROWS FROM TWO OR MORE TABLES BASED ON A RELATED COLUMN BETWEEN THEM
//TYPES OF JOINS
//INNER JOIN: RETURNS RECORDS THAT HAVE MATCHING VALUES IN BOTH TABLES
SELECT FROM STUDENT
FROM STUDENT
INNER JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID;

//LEFT JOIN: RETURNS ALL RECORDS FROM THE LEFT TABLE AND THE MATCHING RECORDS FROM THE RIGHT TABLE
SELECT * FROM STUDENT
FROM STUDENT
LEFT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID;
//RIGHT JOIN: RETURNS ALL RECORDS FROM THE RIGHT TABLE AND THE MATCHING RECORDS FROM THE LEFT TABLE
SELECT * FROM STUDENT
FROM STUDENT
RIGHT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID;
//FULL JOIN: RETURNS ALL RECORDS WHEN THERE IS A MATCH IN EITHER LEFT OR RIGHT
SELECT * FROM STUDENT
FROM STUDENT
LEFT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID;
UNION
SELECT * FROM STUDENT   
FROM STUDENT
RIGHT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID;

//LEFT EXCLUSIVE JOIN
SELECT * FROM STUDENT
FROM STUDENT
LEFT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID
WHERE DEPARTMENT.DEPT_ID IS NULL;//RETURN ALL RECORDS FROM STUDENT TABLE THAT DO NOT HAVE A MATCHING RECORD IN DEPARTMENT TABLE
//RIGHT EXCLUSIVE JOIN
SELECT * FROM STUDENT
FROM STUDENT
RIGHT JOIN DEPARTMENT
ON STUDENT.DEPT_ID = DEPARTMENT.DEPT_ID
WHERE STUDENT.DEPT_ID IS NULL;//RETURN ALL RECORDS FROM DEPARTMENT TABLE THAT DO NOT HAVE A MATCHING RECORD IN STUDENT TABLE
//SELF JOIN: A TABLE IS JOINED WITH ITSELF TO COMBINE ROWS THAT HAVE RELATED DATA
SELECT A.EMP_NAME AS Employee, B.EMP_NAME AS Manager
FROM EMPLOYEE AS A
INNER JOIN EMPLOYEE AS B
ON A.MANAGER_ID = B.EMP_ID;//RETURN A LIST OF EMPLOYEES AND THEIR MANAGERS
WHERE WE USE SELF JOIN
//WHEN EMPLOYEES AND MANAGERS ARE STORED IN THE SAME TABLE

//Union
SELECT NAME, MARK FROM STUDENT WHERE CITY='DHAKA'
UNION
SELECT NAME, MARK FROM STUDENT WHERE CITY='CHITTAGONG';

//subquery
SELECT NAME, MARK FROM STUDENT
WHERE MARK > (SELECT AVG(MARK) FROM STUDENT);//RETURN STUDENTS WHOSE MARK IS GREATER THAN AVERAGE MARK

//OTHER COMPLEX EXAMPLE
SELECT NAME, MARK FROM STUDENT
WHERE CITY = 'DHAKA' AND MARK > (SELECT AVG(MARK) FROM STUDENT WHERE CITY='DHAKA');

//EVEN ROLL NUMBER PRINT 
SELECT NAME, ROLL_NO FROM STUDENT
WHERE ROLL_NO % 2 = 0;

MORE SUBQUERY EXAMPLE
SELECT NAME, MARK FROM STUDENT
WHERE MARK IN (SELECT MARK FROM STUDENT WHERE CITY='DHAKA' AND MARK>70);    
//RETURN STUDENTS WHOSE MARK IS IN THE SET OF MARKS OF STUDENTS FROM DHAKA WITH MARK GREATER THAN 70
SELECT NAME, MARK FROM STUDENT
WHERE ROLL_NO IN (SELECT ROLL_NO FROM STUDENT WHERE ROLL_NO % 2 = 1);
//RETURN STUDENTS WITH ODD ROLL NUMBERS


//MYSQL VIEW
//A VIEW IS A VIRTUAL TABLE BASED ON THE RESULT SET OF A SQL QUERY
CREATE VIEW VIEW_NAME AS
SELECT COLUMN1, COLUMN2, ...

FROM TABLE_NAME
WHERE CONDITION;

DROP VIEW VIEW_NAME;//DELETE THE VIEW